@startuml sprotyvmap
skinparam linetype ortho
package sprotyvmap
{
    package Shared
    {
        package Abstractions
        {
            hide fields
            interface IDataProvider
            {
                GetEquipmentCentreAsync()
                GetAllDistrictsAsync()
            }
            interface IMapPointProvider
            {
                GetPointAsync()
            }
        }
        package Primitives
        {
            hide methods
            struct District
            {
                +Id
                +Name
                +EquipmentCentres
            }
            struct EquipmentCentre
            {
                +Title
                +Information
                +Location
                +Point
            }
            struct MapPoint
            {
                +Latitude
                +Longitude
            }
        }
        District *- EquipmentCentre
        EquipmentCentre o- MapPoint

    }
    package EquipmentCentreService
    {
        package Controllers
        {
            class DistrictsController
            {
                -dataProvider
                -mapPointProvider
                +Get() | api/Districts
                +GetCentre() | api/Districts/{}/centre/{}
            }
            DistrictsController o-- IDataProvider
            DistrictsController o- IMapPointProvider
        }
        package Providers
        {
            class VisicomMapPointProvider
            {
                -httpClient
                +GetPointAsync()
            }
            VisicomMapPointProvider ..|> IMapPointProvider
        }

    }
    package WebApp
    {

        package Services
        {
            interface IEquipmentCentreProvider
            {
                GetDistrictsAsync()
            }
            class ApiEquipmentCentreProvider implements IEquipmentCentreProvider
            {
                -httpClient
                +GetDistrictsAsync()
            }
        }
        package Pages
        {
            class About
            class Main
            {
                -Map
            }
        }
        Main -left-> IEquipmentCentreProvider
    }
}
set separator none
package Visicom.DataApi.Geocoder
{
    package Visicom.DataApi.Abstractions
    {
        interface IGeocoder
        {
            SetOptions()
            GetCoordinates()
            GetCoordinatesAsync()
        }
        interface IRequestOptions
        {
            ApiKey
            Language
            Categories
            ExcludeCategories
            Text
            WordText
            Near
            NearRadius
            Order
            IntersectionArea
            ContainsArea
            Zoom
            Limit
            CountryCode
            CountryCodePriority
        }
    }
    package Data
    {
        hide members
        struct Response
        struct Properties
        struct GeoCentroid
        struct Coordinates
        Response o-- GeoCentroid
        Response o-- Properties
        GeoCentroid o-- Coordinates
    }
    package Enums
    {
        hide methods
        enum Categories
        {
            ItService,
            Cemetery,
            Prisons...
        }
        enum Languages
        {
            Ukrainian,
            English,
            Russian
        }
        enum Order
        {
            Relevance,
            Distance
        }
    }
    class BasicGeocoder implements IGeocoder
    {
        -requestOptions
        -httpClient
        +SetOptions()
        +GetCoordinates()
        +GetCoordinatesAsync()
    }
    class RequestOptions implements IRequestOptions
    {
        ... see IRequestOptions ...
    }
    RequestOptions o-- Enums
    BasicGeocoder --> Data
    BasicGeocoder o-- IRequestOptions
    VisicomMapPointProvider --|> BasicGeocoder
}

@enduml