@startuml sprotyvmap
package sprotyvmap
{
    package Points
    {
        interface IPointProvider {
            GetPoint(district, id)
            GetPointsByDistrict(district)
            GetAllPoints()
        }
        struct Point {
            {field} Title
            Information
            Location
            Coordinates
        }
        IPointProvider -> Point
        class PointProvider implements IPointProvider
        PointProvider -> Point
    }
    package App
    {
        PointController --> IPointProvider
        PointVMorP <- PointController
        PointView -> PointVMorP
    }
    package PointDataScraper
    {
        struct ScrapedData {
            {field}Title
            Information
            Location
        }
        ScrapedData <-- PointProvider
        IPointDataScraper <- PointProvider
        IPointDataScraper -> ScrapedData
        interface IPointDataScraper implements IEnumerator
        class PointDataScraper implements IPointDataScraper
    }

    package Visicom.DataAPI.Geocoder
    {
        interface IGeocoderService {
            GetCoordinates(location)
            ChangeRequestBuilder(requestBuilder)
        }
        IGeocoderService -> IGeocoderRequest
        interface IGeocoderRequest {
            Get()
            SetFormat()
            SetLanguage()
            SetCategories()
            ExcludeCategories()
            SetText()
            SetWordText()
            SetNear()
            SetRadius()
            SetOrder()
            SetIntersectionArea()
            SetContainsArea()
            SetZoom()
            SetLimit()
            SetCountryCode()
            SetCountryCodePriority()
            SetApiKey()
        }
        class GeocoderService implements IGeocoderService{
            RequestBuilder : IGeocoderRequest
            GetCoordinates()
        }
        GeocoderService -> IGeocoderRequest
        PointProvider -down-> IGeocoderService
            package VisicomRequestEnums {
                enum Language {
                    UK
                    RU
                    EN
                }
                enum Order {
                    Asc
                    Desc
                }
                enum Categories {
                    ...
                }
            }
            class VisicomRequest implements IGeocoderRequest{

            }
            VisicomRequest -> VisicomRequestEnums
    }
}

@enduml