
name: Deploy sprotyv-map to Firebase
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/WebService/**'
  workflow_dispatch:
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'sprotyv-map'
      url: https://sprotyvmap.web.app/
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true
      - run: dotnet publish -c ReleaseApp -o src/WebApp/release/ src/WebApp/WebApp.csproj
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPROTYVMAP }}
          channelId: live
          projectId: sprotyvmap
